#!/bin/sh
sudo apt-get update
sudo apt-get upgrade
curl https://get.docker.com | sh
sudo systemctl start docker && sudo systemctl enable docker
docker –version
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker
docker run hello-world
cd /home/$USER
mkdir T
cd T
git clone https://github.com/ApolloAuto/apollo.git
unzip apollo-master.zip -d /home/$USER/T
cd /home/$USER/T/apollo-master/
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh


