#!/bin/sh
docker –v
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker
docker run hello-world
cd /home/$USER
mkdir T
cd T
git clone https://github.com/ApolloAuto/apollo.git
unzip apollo-master.zip -d /home/$USER/T
cd /home/$USER/T/apollo-master/
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh


